routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

/////////////////////////////////clientes/////////////////////////
Route::resource('clientes','ClienteController');
Route::post('/clientes/create', 'ClienteController@store');
Route::put('/{id}', 'ClienteController@update');
/////////////////////////////////ubicaciones/////////////////////////
Route::resource('ubicaciones','UbicacionController');
Route::post('/ubicaciones/create', 'UbicacionController@store');
Route::put('/{id}', 'UbicacionController@update');
////////////////////////////////paquetes//////////////////////////
Route::resource('paquetes','PaqueteController');
Route::post('/paquetes/create', 'PaqueteController@store');
Route::put('/{id}', 'PaqueteController@update');

/////////////////////////////////Citas/////////////////////////
Route::resource('citas','CitaController');
Route::post('/citas/create', 'CitaController@store');
Route::put('/{id}', 'CitaController@update');

/////////////////////////////////mensajes/////////////////////////
Route::resource('mensajes','MensajeController');
//////////////////////////////// mails //////////////////////////
Route::get('/mails','MailController@home');
Route::post('send/email','MailController@sendemail');
/////////////////////////////////usuarios/////////////////////////
Route::resource('usuarios','UsuarioController');
Route::post('/usuarios/create', 'UsuarioController@store');
Route::put('/{id}', 'UsuarioController@update');
/////////////////////////////////cumpleanos/////////////////////////
Route::resource('cumpleanos','CumpleController');
/////////////  exportaciones /////////////////////////////////////
Route::get('exports/excel/gold', 'ExcelController@GoldExcel');
Route::get('exports/excel/cliente', 'ExcelController@ClienteExcel');

app/Ubicaciones.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ubicaciones extends Model
{
	protected $hidden = ['created_at','updated_at'];
    protected $fillable = ['id','nombre_ubicacion','direccion','cp','activo'];
    protected $table = 'ubicacion';

    
}

resources/views/ubicaciones/create.blade.php
@extends('layouts.inicio')

@section('content')

<div class="col-12 grid-margin">
  <div class="card">
    <div class="card-body">
      <form class="form-sample">
        <p class="card-description">
          Informacion de Ubicación
        </p>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group row">
              <label class="col-sm-3 col-form-label">Nombre de la Ubicación</label>
              <div class="col-sm-9">
                <input type="text" class="form-control" value="@isset($ubicacion){{ $ubicacion->nombre_ubicacion }}@endisset" name="nombre_ubicacion"  placeholder="Ingresa el nombre de la ubicacion)" >
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group row">
              <label class="col-sm-3 col-form-label">Direccion</label>
              <div class="col-sm-9">
                <input type="text" class="form-control" value="@isset($ubicacion){{ $ubicacion->direccion }}@endisset" name="direccion" placeholder="Ingresa la direccion">
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          
          <div class="col-md-6">
            <div class="form-group row">
              <label class="col-sm-3 col-form-label">Codigo Postal</label>
              <div class="col-sm-9">
                <input type="text" class="form-control" value="@isset($ubicacion){{ $ubicacion->cp }}@endisset" name="cp" placeholder="Ingresa el codigo postal">
              </div>
            </div>
          </div>

        </div>
        <div class="row">
          <div class="col-md-6">
          	<a href="{{ url('ubicaciones') }}" class="btn btn-inverse-secondary btn-fw"><i class="ti-back-left  menu-icon"></i> Regresar</a>
            <?php 

              if (@isset($ubicacion) == true) { ?>
               <button type="submit" class="btn btn-inverse-primary btn-fw btn-submit"><i class="ti-save  menu-icon"></i> Editar</button>
            <?php }else{ ?>
              <button type="submit" class="btn btn-inverse-primary btn-fw btn-submit"><i class="ti-save  menu-icon"></i> Guardar</button>
            <?php  }
            ?>
          </div>
        
        </div>
      </form>
    </div>
  </div>
</div>


<script type="text/javascript">
    $(".btn-submit").click(function(e){

        e.preventDefault();

        var nombre_ubicacion = $("input[name=nombre_ubicacion]").val();

        var direccion = $("input[name=direccion]").val();

        var cp = $("input[name=cp]").val();



        $.ajax({

           type:"{{ ( isset($ubicacion) ? 'PUT' : 'POST' ) }}",

           url:"{{ ( isset($ubicacion) ) ? '/ubicaciones/' . $ubicacion->id : '/ubicaciones/create' }}",
           headers: {
			      'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
			     },
           data:{
           	nombre_ubicacion:nombre_ubicacion, 
           	direccion:direccion,
           	cp:cp, 
           },
           
            success:function(data){
                swal({title: "Felicidades!", text: data.success, type: "success"}, function(){ location.href ="{{ url('ubicaciones') }}"; } );
            }


        });



  });

</script>
@endsection

resources/views/ubicaciones/index.blade.php
@extends('layouts.inicio')

@section('content')
<div class="col-md-12">
  <div class="box">
    <div class="box-header with-border">
      <h3 class="box-title">Ubicaciones</h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
      <div class="row">
        <div class="col-md-12">
         <a class="btn btn-primary btn-sm" href="{{ route('ubicaciones.create') }}"><i class="ti-plus menu-icon"></i> Nueva Ubicacion</a>
         <div style="height: 5px;"></div>
         <div class="card">
                <div class="card-body">
                  
                  <div class="table-responsive">
                    <table class="table">
			          <thead>
			            <tr>
			             <th>Nombre de la Ubicación</th>
			             <th>Direccion</th>
			             <th>Codigo Postal</th>
			              <th >Acciones</th>
			            </tr>
			          </thead>
			          <tbody>
			            @foreach ($ubicaciones as $ubicacion)
			            <tr>
			                <td>{{ $ubicacion->nombre_ubicacion }}</td>
			                <td>{{ $ubicacion->direccion }}</td>
			                <td>{{ $ubicacion->cp }}</td>
			                <td>

			                	<div class="dropdown">
								  <button class="btn btn-link dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								    <i class="fas fa-bars"></i>
								  </button>
								  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
								    <a class="dropdown-item" href="{{ route('ubicaciones.edit',$ubicacion->id)}}"><i class="ti-pencil  menu-icon"></i> Editar</a>
								    
								    <form action="{{ route('ubicaciones.destroy',$ubicacion->id )}}" method="POST">

			                        @csrf
			                        @method('DELETE')
								    <button class="dropdown-item" type="submit"><i class="ti-trash  menu-icon"></i> Eliminar</button>
								    </form>
								  </div>
								</div>

			                </td>
			            </tr>
			            @endforeach
			          </tbody>
			        </table>
			        {!! $ubicaciones->links() !!}
                  </div>
                </div>
              </div>
        
        </div>
      </div>
      <!-- /.row -->
    </div>
  </div>
  <!-- /.box -->
</div>


@endsection