routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

/////////////////////////////////clientes/////////////////////////
Route::resource('clientes','ClienteController');
Route::post('/clientes/create', 'ClienteController@store');
Route::put('/{id}', 'ClienteController@update');
/////////////////////////////////ubicaciones/////////////////////////
Route::resource('ubicaciones','UbicacionController');
Route::post('/ubicaciones/create', 'UbicacionController@store');
Route::put('/{id}', 'UbicacionController@update');
////////////////////////////////paquetes//////////////////////////
Route::resource('paquetes','PaqueteController');
Route::post('/paquetes/create', 'PaqueteController@store');
Route::put('/{id}', 'PaqueteController@update');

/////////////////////////////////Citas/////////////////////////
Route::resource('citas','CitaController');
Route::post('/citas/create', 'CitaController@store');
Route::put('/{id}', 'CitaController@update');

/////////////////////////////////mensajes/////////////////////////
Route::resource('mensajes','MensajeController');
//////////////////////////////// mails //////////////////////////
Route::get('/mails','MailController@home');
Route::post('send/email','MailController@sendemail');
/////////////////////////////////usuarios/////////////////////////
Route::resource('usuarios','UsuarioController');
Route::post('/usuarios/create', 'UsuarioController@store');
Route::put('/{id}', 'UsuarioController@update');
/////////////////////////////////cumpleanos/////////////////////////
Route::resource('cumpleanos','CumpleController');
/////////////  exportaciones /////////////////////////////////////
Route::get('exports/excel/gold', 'ExcelController@GoldExcel');
Route::get('exports/excel/cliente', 'ExcelController@ClienteExcel');

app/Clientes.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Clientes extends Model
{
	protected $hidden = ['created_at','updated_at'];
    protected $fillable = ['id','nombre_cliente','apellido_paterno','apellido_materno','direccion','cp','fecha_nacimiento','sexo','correo_electronico','telefono','telefono_celular','activo'];
    protected $table = 'clientes';

   public function _Tiposexo(){
    return $this->hasOne('App\TipoSexo', 'id', 'sexo');
  }
    
}

app/Http/Controllers/ClienteController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Clientes;
use App\TipoSexo;




class ClienteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

       $clientes = Clientes::where('activo','1')->orderBy('id')->latest()->paginate(10);

        return view('clientes.index', compact('clientes'))->with('i',(request()->input('page',1)-1)*5);
    }



    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $datos['sexo'] = TipoSexo::where([
                                  ['activo', '=', '1'],
                              ])->orderBy('id')->get();
        return view('clientes.create')->with($datos);        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
            try {
                $cliente = new Clientes();
                $cliente->nombre_cliente = $request->nombre_cliente;
                $cliente->apellido_paterno = $request->apellido_paterno;
                $cliente->apellido_materno = $request->apellido_materno;
                $cliente->direccion = $request->direccion;
                $cliente->cp = $request->cp;
                $cliente->fecha_nacimiento = $request->fecha_nacimiento;
                $cliente->sexo = $request->sexo;
                $cliente->correo_electronico = $request->correo_electronico;
                $cliente->telefono = $request->telefono;
                $cliente->telefono_celular = $request->telefono_celular;
                $cliente->save();
                return response()->json(['success'=>'Se ha Agegado con Exito']);
            } catch (\Exception $e) {
              dd($e->getMessage());
            }
        
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
     public function show()
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $datos['cliente'] = Clientes::find($id);

        $datos['sexo'] = TipoSexo::where([
                                  ['activo', '=', '1'],
                              ])->orderBy('id')->get();
        return view('clientes.create')->with($datos);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {

        try {
            $clientes = Clientes::find($id);
            $clientes->fill($request->all());
            $clientes->save();

        
           return response()->json(['success'=>'Se ha Editado con Exito']);

        } catch (\Exception $e) {
          dd($e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $clientes = Clientes::find($id);
        $clientes->activo = 0;
        $clientes->save();
        
       

        return redirect()->route('clientes.index');
    }






}

resources/views/clientes/create.blade.php
@extends('layouts.inicio')

@section('content')

<div class="col-12 grid-margin">
  <div class="card">
    <div class="card-body">
      <form class="form-sample">
        <p class="card-description">
          Informacion Personal
        </p>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group row">
              <label class="col-sm-3 col-form-label">Nombre(s)</label>
              <div class="col-sm-9">
                <input type="text" class="form-control" value="@isset($cliente){{ $cliente->nombre_cliente }}@endisset" name="nombre_cliente"  placeholder="Ingresa el Nombre(s)" >
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group row">
              <label class="col-sm-3 col-form-label">Apellido Paterno</label>
              <div class="col-sm-9">
                <input type="text" class="form-control" value="@isset($cliente){{ $cliente->apellido_paterno }}@endisset" name="apellido_paterno" placeholder="Ingresa Apellido Paterno">
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          
          <div class="col-md-6">
            <div class="form-group row">
              <label class="col-sm-3 col-form-label">Apellido Materno</label>
              <div class="col-sm-9">
                <input type="text" class="form-control" value="@isset($cliente){{ $cliente->apellido_materno }}@endisset" name="apellido_materno" placeholder="Ingresa Apellido Materno">
              </div>
            </div>
          </div>

          <div class="col-md-6">
            <div class="form-group row">
              <label class="col-sm-3 col-form-label">Sexo</label>
              <div class="col-sm-9">
                <select class="form-control"  name="sexo" >
                @isset($cliente)<option  value="{{ $cliente->sexo }}">{{ $cliente->_Tiposexo->tipo_sexo}}</option>@endisset
                  <option value="0">Selecciona Sexo</option>
                  @foreach ($sexo as $tiposexo)
                    <option value="{{ $tiposexo->id }}">{{ $tiposexo->tipo_sexo }}</option>
                  @endforeach 
                </select>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group row">
              <label class="col-sm-3 col-form-label">Fecha de Nacimiento</label>
              <div class="col-sm-9">
                <input type="text" class="form-control" value="@isset($cliente){{ $cliente->fecha_nacimiento }}@endisset" name="fecha_nacimiento" id="datepicker" placeholder="Ingresa Fecha de Nacimiento">
              </div>
            </div>
          </div>

          <div class="col-md-6">
            <div class="form-group row">
              <label class="col-sm-3 col-form-label">Correo Electronico</label>
              <div class="col-sm-9">
                <input type="email" class="form-control" value="@isset($cliente){{ $cliente->correo_electronico }}@endisset" name="correo_electronico" placeholder="Ingresa Correo Electronico">
              </div>
            </div>
          </div>
          
        </div>
        <p class="card-description">
          Dirección
        </p>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group row">
              <label class="col-sm-3 col-form-label">Direccion</label>
              <div class="col-sm-9">
                <input type="text" class="form-control" value="@isset($cliente){{ $cliente->direccion }}@endisset" name="direccion" placeholder="Ingresa Dirección">
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group row">
              <label class="col-sm-3 col-form-label">Codigo Postal</label>
              <div class="col-sm-9">
                <input type="text" class="form-control" value="@isset($cliente){{ $cliente->cp }}@endisset" name="cp" placeholder="Ingresa Codigo Postal">
              </div>
            </div>
          </div>
          
        </div>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group row">
              <label class="col-sm-3 col-form-label">Telefono Casa</label>
              <div class="col-sm-9">
                <input type="text" class="form-control" value="@isset($cliente){{ $cliente->telefono }}@endisset" name="telefono" placeholder="Ingresa Telefono de Casa">
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group row">
              <label class="col-sm-3 col-form-label">Telefono Celular</label>
              <div class="col-sm-9">
                <input type="text" class="form-control" value="@isset($cliente){{ $cliente->telefono_celular }}@endisset" name="telefono_celular" placeholder="Ingresa Telefono Celular">
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
          	<a href="{{ url('clientes') }}" class="btn btn-inverse-secondary btn-fw"><i class="ti-back-left  menu-icon"></i> Regresar</a>
            <?php 

              if (@isset($cliente) == true) { ?>
               <button type="submit" class="btn btn-inverse-primary btn-fw btn-submit"><i class="ti-save     menu-icon"></i> Editar</button>
            <?php }else{ ?>
              <button type="submit" class="btn btn-inverse-primary btn-fw btn-submit"><i class="ti-save     menu-icon"></i> Guardar</button>
            <?php  }
            ?>
          </div>
        
        </div>
      </form>
    </div>
  </div>
</div>


<script type="text/javascript">
$('#datepicker').datepicker({
      autoclose: true,
      format: 'yyyy-mm-dd',
      isRTL: false,
      lenguaje: 'es-es',
    })

    $(".btn-submit").click(function(e){

        e.preventDefault();

        var nombre_cliente = $("input[name=nombre_cliente]").val();

        var apellido_paterno = $("input[name=apellido_paterno]").val();

        var apellido_materno = $("input[name=apellido_materno]").val();

        var direccion = $("input[name=direccion]").val();

        var cp = $("input[name=cp]").val();

        var fecha_nacimiento = $("input[name=fecha_nacimiento]").val();

        var sexo = $("select[name=sexo]").val();

        var correo_electronico = $("input[name=correo_electronico]").val();

        var telefono = $("input[name=telefono]").val();

        var telefono_celular = $("input[name=telefono_celular]").val();


        $.ajax({

           type:"{{ ( isset($cliente) ? 'PUT' : 'POST' ) }}",

           url:"{{ ( isset($cliente) ) ? '/clientes/' . $cliente->id : '/clientes/create' }}",
           headers: {
			      'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
			     },
           data:{
           	nombre_cliente:nombre_cliente, 
           	apellido_paterno:apellido_paterno,
           	apellido_materno:apellido_materno, 
           	direccion:direccion,
           	cp:cp,
           	fecha_nacimiento:fecha_nacimiento, 
           	sexo:sexo,
           	correo_electronico:correo_electronico, 
           	telefono:telefono,
           	telefono_celular:telefono_celular
           },
           
            success:function(data){
                swal({title: "Felicidades!", text: data.success, type: "success"}, function(){ location.href ="{{ url('clientes') }}"; } );
            }


        });



  });

</script>
@endsection

resources/views/clientes/index.blade.php
@extends('layouts.inicio')

@section('content')
<div class="col-md-12">
  <div class="box">
    <div class="box-header with-border">
      <h3 class="box-title">Clientes</h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
      <div class="row">
        <div class="col-md-12">
         <a class="btn btn-primary btn-sm" href="{{ route('clientes.create') }}"><i class="ti-plus menu-icon"></i> Nuevo Cliente</a>
         <div style="height: 5px;"></div>
         <div class="card">
                <div class="card-body">
                  
                  <div class="table-responsive">
                    <table class="table">
			          <thead>
			            <tr>
			             <th>Nombre del cliente</th>
			             <th>Apellido Paterno</th>
			             <th>Apellido Materno</th>
			             <th>Telefono Celular</th>
			             <th>Direccion</th>
			             <th>Sexo</th>
			              <th >Acciones</th>
			            </tr>
			          </thead>
			          <tbody>
			            @foreach ($clientes as $cliente)
			            <tr>
			                <td>{{ $cliente->nombre_cliente }}</td>
			                <td>{{ $cliente->apellido_paterno }}</td>
			                <td>{{ $cliente->apellido_materno }}</td>
			                <td>{{ $cliente->telefono_celular }}</td>
			                <td>{{ $cliente->direccion }}</td>
			                <td>{{ $cliente->_Tiposexo->tipo_sexo }}</td>
			                <td>

			                	<div class="dropdown">
		                            <button class="btn btn-link dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		                              <i class="fas fa-bars"></i>
		                            </button>
		                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
		                              <a class="dropdown-item" href="{{ route('clientes.edit',$cliente->id)}}"><i class="ti-pencil  menu-icon"></i> Editar</a>
		                              
		                              <form action="{{ route('clientes.destroy',$cliente->id )}}" method="POST">

		                                        @csrf
		                                        @method('DELETE')
		                              <button class="dropdown-item" type="submit"><i class="ti-trash  menu-icon"></i> Eliminar</button>
		                              </form>
		                            </div>
		                          </div>


			                </td>
			            </tr>
			            @endforeach
			          </tbody>
			        </table>
			        {!! $clientes->links() !!}
                  </div>
                </div>
              </div>
        
        </div>
      </div>
      <!-- /.row -->
    </div>
  </div>
  <!-- /.box -->
</div>


@endsection