routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

/////////////////////////////////clientes/////////////////////////
Route::resource('clientes','ClienteController');
Route::post('/clientes/create', 'ClienteController@store');
Route::put('/{id}', 'ClienteController@update');
/////////////////////////////////ubicaciones/////////////////////////
Route::resource('ubicaciones','UbicacionController');
Route::post('/ubicaciones/create', 'UbicacionController@store');
Route::put('/{id}', 'UbicacionController@update');
////////////////////////////////paquetes//////////////////////////
Route::resource('paquetes','PaqueteController');
Route::post('/paquetes/create', 'PaqueteController@store');
Route::put('/{id}', 'PaqueteController@update');

/////////////////////////////////Citas/////////////////////////
Route::resource('citas','CitaController');
Route::post('/citas/create', 'CitaController@store');
Route::put('/{id}', 'CitaController@update');

/////////////////////////////////mensajes/////////////////////////
Route::resource('mensajes','MensajeController');
//////////////////////////////// mails //////////////////////////
Route::get('/mails','MailController@home');
Route::post('send/email','MailController@sendemail');
/////////////////////////////////usuarios/////////////////////////
Route::resource('usuarios','UsuarioController');
Route::post('/usuarios/create', 'UsuarioController@store');
Route::put('/{id}', 'UsuarioController@update');
/////////////////////////////////cumpleanos/////////////////////////
Route::resource('cumpleanos','CumpleController');
/////////////  exportaciones /////////////////////////////////////
Route::get('exports/excel/gold', 'ExcelController@GoldExcel');
Route::get('exports/excel/cliente', 'ExcelController@ClienteExcel');

app/Paquetes.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Paquetes extends Model
{
	protected $hidden = ['created_at','updated_at'];
    protected $fillable = ['id','nombre_paquete','precio_paquete','descripcion_paquete','activo'];
    protected $table = 'paquetes';

    
}

app/Http/Controllers/PaqueteController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Paquetes;




class PaqueteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

       $paquetes = Paquetes::where('activo','1')->orderBy('id')->latest()->paginate(10);

        return view('paquetes.index', compact('paquetes'))->with('i',(request()->input('page',1)-1)*5);
    }



    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
        return view('paquetes.create');        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
            try {
                $cliente = new Paquetes();
                $cliente->nombre_paquete = $request->nombre_paquete;
                $cliente->precio_paquete = $request->precio_paquete;
                $cliente->descripcion_paquete = $request->descripcion_paquete;
                $cliente->save();
                return response()->json(['success'=>'Se ha Agegado con Exito']);
            } catch (\Exception $e) {
              dd($e->getMessage());
            }
        
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
     public function show()
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $datos['paquete'] = Paquetes::find($id);
        return view('paquetes.create')->with($datos);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {

        try {
            $paquetes = Paquetes::find($id);
            $paquetes->fill($request->all());
            $paquetes->save();

        
           return response()->json(['success'=>'Se ha Editado con Exito']);

        } catch (\Exception $e) {
          dd($e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $paquetes = Paquetes::find($id);
        $paquetes->activo = 0;
        $paquetes->save();
        
       

        return redirect()->route('paquetes.index');
    }






}

resources/views/paquetes/create.blade.php
@extends('layouts.inicio')

@section('content')

<div class="col-12 grid-margin">
  <div class="card">
    <div class="card-body">
      <form class="form-sample">
        <p class="card-description">
          Informacion de Paquete
        </p>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group row">
              <label class="col-sm-3 col-form-label">Nombre del Paquete</label>
              <div class="col-sm-9">
                <input type="text" class="form-control" value="@isset($paquete){{ $paquete->nombre_paquete }}@endisset" name="nombre_paquete"  placeholder="Ingresa el nombre de la paquete)" >
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group row">
              <label class="col-sm-3 col-form-label">Precio</label>
              <div class="col-sm-9">
                <input type="text" class="form-control" value="@isset($paquete){{ $paquete->precio_paquete }}@endisset" name="precio_paquete" placeholder="Ingresa la precio">
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          
          <div class="col-md-6">
            <div class="form-group row">
              <label class="col-sm-3 col-form-label">Descripción</label>
              <div class="col-sm-9">
                <textarea name="descripcion_paquete" class="form-control" rows="5">@isset($paquete){{ $paquete->descripcion_paquete }}@endisset</textarea>
                
              </div>
            </div>
          </div>

        </div>
        <div class="row">
          <div class="col-md-6">
          	<a href="{{ url('paquetes') }}" class="btn btn-inverse-secondary btn-fw"><i class="ti-back-left  menu-icon"></i> Regresar</a>
            <?php 

              if (@isset($paquete) == true) { ?>
               <button type="submit" class="btn btn-inverse-primary btn-fw btn-submit"><i class="ti-save  menu-icon"></i> Editar</button>
            <?php }else{ ?>
              <button type="submit" class="btn btn-inverse-primary btn-fw btn-submit"><i class="ti-save  menu-icon"></i> Guardar</button>
            <?php  }
            ?>
          </div>
        
        </div>
      </form>
    </div>
  </div>
</div>


<script type="text/javascript">
    $(".btn-submit").click(function(e){

        e.preventDefault();

        var nombre_paquete = $("input[name=nombre_paquete]").val();

        var precio_paquete = $("input[name=precio_paquete]").val();

        var descripcion_paquete = $("textarea[name=descripcion_paquete]").val();



        $.ajax({

           type:"{{ ( isset($paquete) ? 'PUT' : 'POST' ) }}",

           url:"{{ ( isset($paquete) ) ? '/paquetes/' . $paquete->id : '/paquetes/create' }}",
           headers: {
			      'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
			     },
           data:{
           	nombre_paquete:nombre_paquete, 
           	precio_paquete:precio_paquete,
           	descripcion_paquete:descripcion_paquete, 
           },
           
            success:function(data){
                swal({title: "Felicidades!", text: data.success, type: "success"}, function(){ location.href ="{{ url('paquetes') }}"; } );
            }


        });



  });

</script>
@endsection

resources/views/paquetes/index.blade.php
@extends('layouts.inicio')

@section('content')
<div class="col-md-12">
  <div class="box">
    <div class="box-header with-border">
      <h3 class="box-title">Paquetes</h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
      <div class="row">
        <div class="col-md-12">
         <a class="btn btn-primary btn-sm" href="{{ route('paquetes.create') }}"><i class="ti-plus menu-icon"></i> Nuevo Paquete</a>
         <div style="height: 5px;"></div>
         <div class="card">
                <div class="card-body">
                  
                  <div class="table-responsive">
                    <table class="table">
                <thead>
                  <tr>
                   <th>Nombre Paquete</th>
                   <th>Precio Paquete</th>
                    <th >Acciones</th>
                  </tr>
                </thead>
                <tbody>
                  @foreach ($paquetes as $paquete)
                  <tr>
                      <td>{{ $paquete->nombre_paquete }}</td>
                      <td>${{ $paquete->precio_paquete }}</td>
                      <td>
                          <div class="dropdown">
                            <button class="btn btn-link dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              <i class="fas fa-bars"></i>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                              <a class="dropdown-item" href="{{ route('paquetes.edit',$paquete->id)}}"><i class="ti-pencil  menu-icon"></i> Editar</a>
                              
                              <form action="{{ route('paquetes.destroy',$paquete->id )}}" method="POST">

                                        @csrf
                                        @method('DELETE')
                              <button class="dropdown-item" type="submit"><i class="ti-trash  menu-icon"></i> Eliminar</button>
                              </form>
                            </div>
                          </div>


                      </td>
                  </tr>
                  @endforeach
                </tbody>
              </table>
              {!! $paquetes->links() !!}
                  </div>
                </div>
              </div>
        
        </div>
      </div>
      <!-- /.row -->
    </div>
  </div>
  <!-- /.box -->
</div>


@endsection