routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

/////////////////////////////////clientes/////////////////////////
Route::resource('clientes','ClienteController');
Route::post('/clientes/create', 'ClienteController@store');
Route::put('/{id}', 'ClienteController@update');
/////////////////////////////////ubicaciones/////////////////////////
Route::resource('ubicaciones','UbicacionController');
Route::post('/ubicaciones/create', 'UbicacionController@store');
Route::put('/{id}', 'UbicacionController@update');
////////////////////////////////paquetes//////////////////////////
Route::resource('paquetes','PaqueteController');
Route::post('/paquetes/create', 'PaqueteController@store');
Route::put('/{id}', 'PaqueteController@update');

/////////////////////////////////Citas/////////////////////////
Route::resource('citas','CitaController');
Route::post('/citas/create', 'CitaController@store');
Route::put('/{id}', 'CitaController@update');

/////////////////////////////////mensajes/////////////////////////
Route::resource('mensajes','MensajeController');
//////////////////////////////// mails //////////////////////////
Route::get('/mails','MailController@home');
Route::post('send/email','MailController@sendemail');
/////////////////////////////////usuarios/////////////////////////
Route::resource('usuarios','UsuarioController');
Route::post('/usuarios/create', 'UsuarioController@store');
Route::put('/{id}', 'UsuarioController@update');
/////////////////////////////////cumpleanos/////////////////////////
Route::resource('cumpleanos','CumpleController');
/////////////  exportaciones /////////////////////////////////////
Route::get('exports/excel/gold', 'ExcelController@GoldExcel');
Route::get('exports/excel/cliente', 'ExcelController@ClienteExcel');

app/Citas.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Citas extends Model
{
	protected $hidden = ['created_at','updated_at'];
    protected $fillable = ['id','num_cliente ','num_paquete','num_ubicacion','fecha_cita','estatus_cita','activo'];
    protected $table = 'citas';


      public function _NombreCliente(){
	    return $this->hasOne('App\Clientes', 'id', 'num_cliente');
	  }

	  public function _Paquete(){
	    return $this->hasOne('App\Paquetes', 'id', 'num_paquete');
	  }

	  public function _Ubicacion(){
	    return $this->hasOne('App\Ubicaciones', 'id', 'num_ubicacion');
	  }

	  public function _Estatus(){
	    return $this->hasOne('App\EstatusCita', 'id', 'estatus_cita');
	  }

}

app/Http/Controllers/CitaController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Citas;
use App\Ubicaciones;
use App\Paquetes;
use App\Clientes;
use App\EstatusCita;
use Illuminate\Support\Facades\DB;



class CitaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

       $citas = Citas::where([['activo','1'],['estatus_cita','1']])->orwhere([['activo','1'],['estatus_cita','2']])->orderBy('fecha_cita','DESC')->latest()->paginate(10);

        return view('citas.index', compact('citas'))->with('i',(request()->input('page',1)-1)*5);
    }



    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $datos['ubicacion'] = Ubicaciones::where([
                                  ['activo', '=', '1'],
                              ])->orderBy('id')->get();
        $datos['paquete'] = Paquetes::where([
                                  ['activo', '=', '1'],
                              ])->orderBy('id')->get();
        $datos['cliente'] = Clientes::where([
                                  ['activo', '=', '1'],
                              ])->orderBy('id')->get();
        $datos['estatus'] = EstatusCita::orderBy('id')->get();


        $mes = date('m');
        $anio = date('Y');
        $numero = cal_days_in_month(CAL_GREGORIAN, date('m'), date('Y'));

     

       $datos['fecha'] = DB::select("SELECT * FROM citas WHERE fecha_cita BETWEEN '".$anio."-".$mes."-01' and '".$anio."-".$mes."-".$numero."' AND estatus_cita = '1' OR estatus_cita = '2' order by fecha_cita DESC ");



        return view('citas.create')->with($datos);        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
            try {
                $cliente = new Citas();
                $cliente->num_cliente = $request->num_cliente;
                $cliente->num_paquete = $request->num_paquete;
                $cliente->num_ubicacion = $request->num_ubicacion;
                $cliente->fecha_cita = $request->fecha_cita;
                $cliente->estatus_cita = '1';
                
                $cliente->save();
                return response()->json(['success'=>'Se ha Agegado con Exito']);
            } catch (\Exception $e) {
              dd($e->getMessage());
            }
        
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
     public function show($id)
    {
        $cita = Citas::find($id);

        $datos['citas'] = Citas::find($id);
        $datos['cliente_id'] = Clientes::where([
                                  ['activo', '=', '1'],
                                  ['id', '=', $cita->num_cliente],
                              ])->orderBy('id')->get();

        $datos['ubicacion_id'] = Ubicaciones::where([
                                  ['activo', '=', '1'],
                                  ['id', '=', $cita->num_ubicacion],
                              ])->orderBy('id')->get();
        $datos['paquete'] = Paquetes::where([
                                  ['activo', '=', '1'],
                                  ['id', '=', $cita->num_paquete],
                              ])->orderBy('id')->get();



        return view('citas.show')->with($datos);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $datos['cita'] = Citas::find($id);

        $datos['ubicacion'] = Ubicaciones::where([
                                  ['activo', '=', '1'],
                              ])->orderBy('id')->get();
        $datos['paquete'] = Paquetes::where([
                                  ['activo', '=', '1'],
                              ])->orderBy('id')->get();
        $datos['cliente'] = Clientes::where([
                                  ['activo', '=', '1'],
                              ])->orderBy('id')->get();
        $datos['estatus'] = EstatusCita::orderBy('id')->get();

        $mes = date('m');
        $anio = date('Y');
        $numero = cal_days_in_month(CAL_GREGORIAN, date('m'), date('Y'));

        $datos['fecha'] = DB::select("SELECT * FROM citas WHERE fecha_cita BETWEEN '".$anio."-".$mes."-01' and '".$anio."-".$mes."-".$numero."' AND estatus_cita = '1' order by fecha_cita DESC ");

        return view('citas.create')->with($datos);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {

        try {
            $citas = Citas::find($id);

            $citas->fill($request->all());
            $citas->save();

        
           return response()->json(['success'=>'Se ha Editado con Exito']);

        } catch (\Exception $e) {
          dd($e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $citas = Citas::find($id);
        $citas->activo = 0;
        $citas->save();
        
       

        return redirect()->route('citas.index');
    }






}

resources/views/citas/create.blade.php
@extends('layouts.inicio')

@section('content')

<div class="col-12 grid-margin">
  <div class="card">
    <div class="card-body">
      <form class="form-sample">
        <p class="card-description">
          Informacion De Cita
        </p>
        <?php 
          if (@isset($cita) == true) { ?>
            
        <?php }else{ ?>
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                  <div class="card-body">
                    <h4 class="card-title">Agenda de Citas</h4>
                    
                    <div class="table-responsive" style="width: 100%;height: 280px;overflow: scroll;">
                      <table class="table table-hover">
                        <thead>
                          <tr>
                            <th>
                              Dia
                            </th>
                            <th>
                             Mes
                            </th>
                            <th>
                             Año
                            </th>
                            <th>
                             Hora
                            </th>
                            <th>
                             Estatus
                            </th>
                          </tr>
                        </thead>
                        <tbody>
                          @foreach ($fecha as $fechas)
                          <tr>
                            <?php  

                            list($fecha_actual,$hora) = explode(' ', $fechas->fecha_cita);
                            list($anio,$mes,$dia) = explode('-', $fecha_actual);

                            ?>
                            <td>{{ $dia }}</td>
                            <td>
                              <?php 

                              if ($mes == 1) {
                                echo 'Enero';

                              }elseif($mes == 2){
                                echo 'Febrero';

                              }elseif($mes == 3){
                                echo 'Marzo';

                              }elseif($mes == 4){
                                echo 'Abril';

                              }elseif($mes == 5){
                                echo 'Mayo';

                              }elseif($mes == 6){
                                echo 'Junio';

                              }elseif($mes == 7){
                                echo 'Julio';

                              }elseif($mes == 8){
                                echo 'Agosto';

                              }elseif($mes == 9){
                                echo 'Septiembre';

                              }elseif($mes == 10){
                                echo 'Octubre';

                              }elseif($mes == 11){
                                echo 'Noviembre';

                              }elseif($mes == 12){
                                echo 'Diciembre';

                              }
                              ?>
                            </td>
                            <td>{{ $anio }}</td>
                            <td>{{ $hora }}</td>
                            <td>
                            <?php 

                            if ($fechas->estatus_cita == 1) {
                              echo '<label class="badge badge badge-success">Abierta</label>';
                            }elseif($fechas->estatus_cita == 2){
                              echo  '<label class="badge badge-danger">Suspendida</label>';
                            }

                            ?>
                            </td>
                          </tr>
                          @endforeach 
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
            </div>
        <?php  }

         ?>
        
        <div style="height: 30px;"></div>
         <p class="card-description">
            Creación de Cita
          </p>
        <div class="row">
         
            <div class="col-md-6">
            <div class="form-group row">
              <label class="col-sm-3 col-form-label">Ubicacion</label>
              <div class="col-sm-9">
                <select class="form-control"  name="num_ubicacion" >
                @isset($cita)<option  value="{{ $cita->num_ubicacion }}">{{ $cita->_Ubicacion->nombre_ubicacion }}</option>@endisset
                  <option value="0">Selecciona Ubicacion</option>
                  @foreach ($ubicacion as $tipoubicacion)
                    <option value="{{ $tipoubicacion->id }}">{{ $tipoubicacion->nombre_ubicacion }}</option>
                  @endforeach 
                </select>
              </div>
            </div>
          </div>
          
          <div class="col-md-6">
            <div class="form-group row">
              <label class="col-sm-3 col-form-label">Paquete</label>
              <div class="col-sm-9">
                <select class="form-control"  name="num_paquete" >
                @isset($cita)<option  value="{{ $cita->num_paquete }}">{{ $cita->_Paquete->nombre_paquete }}</option>@endisset
                  <option value="0">Selecciona Paquete</option>
                  @foreach ($paquete as $tipopaquete)
                    <option value="{{ $tipopaquete->id }}">{{ $tipopaquete->nombre_paquete }},${{ $tipopaquete->precio_paquete }}</option>
                  @endforeach 
                </select>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          
          
          <div class="col-md-6">
            <div class="form-group row">
              <label class="col-sm-3 col-form-label">Nombre del Cliente</label>
              <div class="col-sm-9">
                <select class="form-control"  name="num_cliente" >
                @isset($cita)<option  value="{{ $cita->num_cliente }}">{{ $cita->_NombreCliente->nombre_cliente }} {{ $cita->_NombreCliente->apellido_paterno }} {{ $cita->_NombreCliente->apellido_materno }}</option>@endisset
                  <option value="0">Selecciona Nombre del Cliente</option>
                  @foreach ($cliente as $tipocliente)
                    <option value="{{ $tipocliente->id }}">{{ $tipocliente->nombre_cliente  }} {{ $tipocliente->apellido_paterno  }} {{ $tipocliente->apellido_materno  }}</option>
                  @endforeach 
                </select>
              </div>
            </div>
          </div>

         
          <div class="col-md-6">
            <div class="form-group row">
              <label class="col-sm-3 col-form-label">Fecha Cita</label>
              <div class="col-sm-9">
                <div class="form-group">
                  <input class="form-control " name="fecha_cita" type="text" id="datetimepicker" value="@isset($cita){{ $cita->fecha_cita }}@endisset" placeholder="Ingresa la Fecha y Hora">
                </div>
              </div>
            </div>
          </div>

        </div>
        
         <?php 

          if (@isset($cita) == true) { ?>

        <div class="row">
          
          
            <div class="col-md-6">
            <div class="form-group row">
              <label class="col-sm-3 col-form-label">Estatus de Cita</label>
              <div class="col-sm-9">
                <select class="form-control"  name="estatus_cita" >
                @isset($cita)<option  value="{{ $cita->estatus_cita }}">{{ $cita->_Estatus->nombre_estatus_cita }}</option>@endisset
                  <option value="0">Selecciona Estatus Cita</option>
                  @foreach ($estatus as $tipostatus)
                    <option value="{{ $tipostatus->id }}">{{ $tipostatus->nombre_estatus_cita  }} </option>
                  @endforeach 
                </select>
              </div>
            </div>
          </div>

        </div>
        <?php 
          }else{
            
          }
        ?>


        <div class="row">
          <div class="col-md-6">
          	<a href="{{ url('citas') }}" class="btn btn-inverse-secondary btn-fw"><i class="ti-back-left  menu-icon"></i> Regresar</a>
            <?php 

              if (@isset($cita) == true) { ?>
               <button type="submit" class="btn btn-inverse-primary btn-fw btn-submit"><i class="ti-save     menu-icon"></i> Editar</button>
            <?php }else{ ?>
              <button type="submit" class="btn btn-inverse-primary btn-fw btn-submit"><i class="ti-save     menu-icon"></i> Guardar</button>
            <?php  }
            ?>
          </div>
        
        </div>
      </form>
    </div>
  </div>
</div>


<script type="text/javascript">
$("#datetimepicker").datetimepicker({
  
    showMeridian: true,
    startView: 1,
    maxView: 1,
    format: 'yyyy-mm-dd hh:mm:ss',
    
    autoclose: true,
   
  });

    $(".btn-submit").click(function(e){

        e.preventDefault();

        var num_ubicacion = $("select[name=num_ubicacion]").val();

        var num_paquete = $("select[name=num_paquete]").val();

        var num_cliente = $("select[name=num_cliente]").val();

        var fecha_cita = $("input[name=fecha_cita]").val();

        var estatus_cita = $("select[name=estatus_cita]").val();



        $.ajax({

           type:"{{ ( isset($cita) ? 'PUT' : 'POST' ) }}",

           url:"{{ ( isset($cita) ) ? '/citas/' . $cita->id : '/citas/create' }}",
           headers: {
			      'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
			     },
           data:{
           	num_ubicacion:num_ubicacion, 
           	num_paquete:num_paquete,
           	num_cliente:num_cliente, 
            fecha_cita:fecha_cita,
           	estatus_cita:estatus_cita,
           	
           },
           
            success:function(data){
              swal({title: "Felicidades!", text: data.success, type: "success"}, function(){ location.href ="{{ url('citas') }}"; } );
            }


        });



  });

</script>
@endsection

resources/views/citas/index.blade.php
@extends('layouts.inicio')

@section('content')
<div class="col-md-12">
  <div class="box">
    <div class="box-header with-border">
      <h3 class="box-title">Citas</h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
      <div class="row">
        <div class="col-md-12">
         <a class="btn btn-primary btn-sm" href="{{ route('citas.create') }}"><i class="ti-plus menu-icon"></i> Nueva Cita</a>
         <div style="height: 5px;"></div>
         <div class="card">
                <div class="card-body">
                  
                  <div class="table-responsive">
                    <table class="table">
			          <thead>
			            <tr>
			             <th>Nombre del cliente</th>
			             <th>Paquete</th>
			             <th>Ubicación</th>
			             <th>Fecha</th>
			             <th>Estatus</th>
			              <th >Acciones</th>
			            </tr>
			          </thead>
			          <tbody>
			            @foreach ($citas as $cita)
			            <tr>
			                <td>{{ $cita->_NombreCliente->nombre_cliente }} {{ $cita->_NombreCliente->apellido_paterno }} {{ $cita->_NombreCliente->apellido_materno }}</td>
			                <td>{{ $cita->_Paquete->nombre_paquete }}</td>
			                <td>{{ $cita->_Ubicacion->nombre_ubicacion }}</td>
			                <td>{{ $cita->fecha_cita }}</td>
			                <td>
			                	<?php 

			                		if ($cita->_Estatus->nombre_estatus_cita == "Abierta") {
			                			echo '<label class="badge badge badge-success">'.$cita->_Estatus->nombre_estatus_cita.'</label>';
			                		}elseif($cita->_Estatus->nombre_estatus_cita == "Suspendida"){
			                			echo  '<label class="badge badge-danger">'.$cita->_Estatus->nombre_estatus_cita.'</label>';
			                		}

			                	 ?>
			                	 
			               	</td>
			                
			                <td>
			                    <div class="dropdown">
								  <button class="btn btn-link dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								    <i class="fas fa-bars"></i>
								  </button>
								  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
								    <a class="dropdown-item" href="{{ route('citas.edit',$cita->id)}}"><i class="ti-pencil  menu-icon"></i> Editar</a>
								    <a class="dropdown-item" href="{{ route('citas.show',$cita->id)}}"><i class="fas fa-file-invoice"></i> Contrato</a>
								    <form action="{{ route('citas.destroy',$cita->id )}}" method="POST">

			                        @csrf
			                        @method('DELETE')
								    <button class="dropdown-item" type="submit"><i class="ti-trash  menu-icon"></i> Eliminar</button>
								    </form>
								  </div>
								</div>

			                </td>

			            </tr>
			            @endforeach
			          </tbody>
			        </table>
			        {!! $citas->links() !!}
                  </div>
                </div>
              </div>
        
        </div>
      </div>
      <!-- /.row -->
    </div>
  </div>
  <!-- /.box -->
</div>


@endsection